### ISSUE TITLE
[feat] Create Reusable Text Generation Function

### ISSUE THREAD

**Issue by BeauBouchard** [BeauBouchard/garden-quest#4]
Create a reusable function that will accept a X/Y coordinate to place the start of the left upper corner of the sprite array. 

It should accept up to 16 characters, future functionality can be to create rows which will allow for spacing of larger quantities of text. 

#### Garbage Collection

Must have a way to clear itself from the screen, possibly creating a list to track open texts or a cleanup bulk function to remove all texts from list. 

### Tasks
* [ ] Create a reusable function `PlaceText`
* [ ] Accepts X and Y params for upper left corner of first sprite
* [ ] Accepts `message` an string or array of chars up to 16 characters
* [ ] returns ...
